name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swift API Diff
      uses: ltetzlaff/swift-api-diff@v1.0.0
